In [4]:
# L'estensione del file .ipynb permette di organizzare il codice in celle

import numpy as np

a = np.array([1,2,3])  #questo li considera numeri
b = [1,2,3] #questo lo considera un'array e moltiplica per 3 gli indici
c = np.array([1,2,3])


print(a*5)
print(b*3)
print(a*c)
print(c*b)
print(a+c)
print(a ** c)
print("----------------------------------")

r = np.arange(10)  #crea un array di 10 
print(r[2:8:3])
print(r[::-1])
r[3:7] = 99 
print(r)
print("----------------------------------")
I = np.array([[1,2,3], [0,0,0],[3,2,1]])
print(len(I.shape), I.shape)
I[0:2, 0:2] += 5
print(I[0:2, 0:2]) #sottomatrice della matrice di partenza
print(I)


print("----------------------------------")
for row in I:
    for col in row:
        print(col)
print("----------------------------------")
for x in np.nditer(I): #itera
    print(x)

for x in I.flatten(): #appiattisce
    print(x)
 
for pos, x in np.ndenumerate(I):
    print(pos,x)
    i,j = pos #l'indice è una tupla poichè ho una matrice bidimensionale
    # x =0
    # I[i,j]=0  reset matrice
print("--------------------------------")
#Trasposizione di immagine
print("Matrice trasposta")
F = I.copy() #creo una copia
for pos, x in np.ndenumerate(I):
    i, j = pos
    F[j,i] = x #x = I[i,j]

    print(F)




[ 5 10 15]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1 4 9]
[1 4 9]
[2 4 6]
[ 1  4 27]
----------------------------------
[2 5]
[9 8 7 6 5 4 3 2 1 0]
[ 0  1  2 99 99 99 99  7  8  9]
----------------------------------
2 (3, 3)
[[6 7]
 [5 5]]
[[6 7 3]
 [5 5 0]
 [3 2 1]]
----------------------------------
6
7
3
5
5
0
3
2
1
----------------------------------
6
7
3
5
5
0
3
2
1
6
7
3
5
5
0
3
2
1
(0, 0) 6
(0, 1) 7
(0, 2) 3
(1, 0) 5
(1, 1) 5
(1, 2) 0
(2, 0) 3
(2, 1) 2
(2, 2) 1
--------------------------------
Matrice trasposta
[[6 7 3]
 [5 5 0]
 [3 2 1]]
[[6 7 3]
 [7 5 0]
 [3 2 1]]
[[6 7 3]
 [7 5 0]
 [3 2 1]]
[[6 5 3]
 [7 5 0]
 [3 2 1]]
[[6 5 3]
 [7 5 0]
 [3 2 1]]
[[6 5 3]
 [7 5 0]
 [3 0 1]]
[[6 5 3]
 [7 5 0]
 [3 0 1]]
[[6 5 3]
 [7 5 2]
 [3 0 1]]
[[6 5 3]
 [7 5 2]
 [3 0 1]]


In [5]:
#Creare un'immagine

I = np.arange(40000) #array monodimensionale, quindi uso una funzione che si chiama reshape()
I = I.reshape((200,200))

import cv2

cv2.imshow("I",I/40000)
cv2.waitKey(0)



-1